stages:
  download_data:
    cmd: wget -O data/spam.csv https://www.dropbox.com/s/68edi5r8xn9lw46/spam.csv?dl=1
    outs:
      - data/spam.csv

  fit_model:
    cmd: python fit_model.py
    deps:
      - fit_model.py
      - data/spam.csv
    outs:
      - models/cv.pickle
      - models/rfc.onnx
      - data/X_train.pickle
      - data/X_test.pickle
      - data/y_train.pickle
      - data/y_test.pickle
    params:
      - feature_storage.n_estimators
      
  inference_model:
    cmd: python test_model.py
    deps:
      - models/rfc.onnx
      - data/X_train.pickle
      - data/X_test.pickle
      - data/y_train.pickle
      - data/y_test.pickle
    metrics:
      - metrics/metrics.json
    plots:
      - metrics/plots/roc_auc.csv:
          x: fpr
          y: tpr
    